### ISSUE TITLE
maintaining consistency in "loot" commands with budabot and users expectations

### ISSUE THREAD

**Issue by Teeko1993** [Budabot/Tyrbot#18]
Currently the help for the loot command looks like this: Show the list of added items with suggestions in parenthesis
Show the list of added items:
    !loot (should be !loot list for consistency)
Clear all loot:
    !loot clear
Remove existing loot:
    !loot remitem item_index
Add an item to loot list:
    !loot additem item [item_count] (This should be !loot <item link/name> here and it should auto recognize item names like budabot did. Also, if the same item is added twice, it adds it in two seperate listings, instead of increasing the item count, as budabot did. The budabot behavior was more intuitive to users and is the understood behavior)
Increase item count:
    !loot increase item_index
Decrease item count:
    !loot decrease item_index
Add yourself to item:
    !loot add item_index
Remove yourself from item:
    !loot rem
Roll all loot:
    !loot roll
Rebuild loot list:
    !loot reroll
Used by the loot lists to add items to loot list:
    !loot additem raid item_id item_count (this isn't very clear how this works even)
Add all loot from given raid:
    !loot addraid raid category (also not sure how this even works, I'm assuming these two commands work in conjunction with the raid module?)

**Comment by KristinHansen** [comment]
I'm working on rewriting this, and while some of your suggestions probably will make it in the final version, there are others that won't. I'll specify when I've come around to actually fix it (currently it's just a new branch... with a few modifications, so not much to speak of).

I'll probably start this week, as I got some vacation coming up, and should have some spare time.

**Comment by bigwheels16** [comment]
I have a couple hard requirements for the !loot command.

1) For `!loot additem <item>` the additem needs to be optional, so this command handler probably needs to be the last one in the file.  I took a lot of flak for deviating from this in Budabot, and that is partly because Budabot does not have good support for optional params.  But Tyrbot does not have that limitation so we can rectify this now.

2) `!loot add` needs to be able to accept raw strings, that may or may not resolve to actual items.  For item refs, I don't care if it adds special handling for those or if it just treats them as strings.  For the optional count param at the end, we might want to consider using what I call a "named parameter".  Example: `!loot add <item> --count=2`.  This is done in a few other places in the bot with good success and would avoid problems where people are trying to add an items with a number in the name that gets interpreted as a count.  Whether that is appropriate here I am not sure but it should be considered.

**Comment by bigwheels16** [comment]
> Show the list of added items:
!loot (should be !loot list for consistency)

In Budabot, `!loot` showed the list of items on the loot list.  `!list` was an alias for !loot, but `!loot list` it not recognize, at least on Budabot 4.  Maybe an earlier version?

**Comment by bigwheels16** [comment]
@Teeko1993 can you test the changes I have made to the !loot command and then close this ticket?  And then if there are still any issues remaining, create a new ticket with just the issues remaining.  I know that it does not auto detect items like Budabot did, but I think everything else is fixed/solved now.

**Comment by bigwheels16** [comment]
Going to consider this done for now
