### ISSUE TITLE
Discord Module Relay Settings vs Events Inconsistency

### ISSUE THREAD

**Issue by Teeko1993** [Budabot/Tyrbot#24]
When setting up the discord module, the setting "Global setting for relaying of Discord messages to the private channel" is a one way setting. It only disables the relaying of discord messages TO the private channel, To disable private channel messages being relayed to the discord, you have to disable the event "private_channel_message - Relay messages to Discord from private channel".

This issue applies to the org channel setting/event in the same window as well.

**Comment by KristinHansen** [comment]
Minor bug, I'll fix this tomorrow.

**Comment by bigwheels16** [comment]
@KristinHansen this is a good example of why I was considering removing events from the config, and have them be more of an internal implementation detail.  and then have Boolean settings the controller for whether events are enabled or not.  obviously, we would need a callback pattern for settings when their values changed in order for this to work.  So if we have a setting called "private_channel_relay", when that value is changed, we would have one or more callbacks defined that are trigger and one of those callbacks would either register an event for listening to private channel and org channel messages, or de-register it.  This also allows multiple events to be controlled through a single gate.  I haven't worked it all out in my mind yet, but hopefully this makes sense.  Maybe you will think of something while you are working on this.

I realize that in this case, the state for controlling which channels are being relayed is stored in the db rather than in settings, so a solution might not work here in any case, but the pattern is similar at least.

**Comment by bigwheels16** [comment]
I've added the ability to hide events, which should make this easier to solve

**Comment by bigwheels16** [comment]
this is mostly solved now
