### ISSUE TITLE
Topic

### ISSUE THREAD

**Issue by Teeko1993** [Budabot/Tyrbot#35]
Topic does not spam to people upon login or joining the private channel, as it did in budabot. This is typically used as a message upon login that people do not need to click on, like they do news, and also(for raid bots) any information that should be communicated to users upon joining. Is this intended behavior or a bug? When should the topic be sent to users?

**Comment by bigwheels16** [comment]
In Budabot, the difference between !topic and !news was obscured, and often they were used interchangeably.  One of the goals of Tyrbot is to reduce logon spam.  So for this reason, the news module has added functionality with the ability to mark news items as read so they don't continually appear.  This also makes it so that new news items stand out and are more likely to be read.

!topic is meant to be extremely temporary (a particular topic might be good for a few hours). It should only apply to chars joining the private channel (not the org channel), and only when the bot is used as a raid bot.  The topic command should be enhanced so that the topic is automatically cleared when the last player leaves the private channel, or perhaps when the raid leader leaves the channel.

So if the desire for !topic is to be used for news, that doesn't require clicking on a link to open a blob window, I would rather enhance the news module with that functionality.

However, !topic should probably still be enhanced to show to chars joining the private channel, if it does not do that already.

**Comment by Teeko1993** [comment]
That makes sense, and I don't have any reason why that wouldn't work that way. A new usage for this could be a "message of the day" and limited to a certain number of characters to reduce that login spam.

**Comment by bigwheels16** [comment]
@Teeko1993 so what still needs to be done for this then?

**Comment by Teeko1993** [comment]
Topic doesn't spam when you join the channel. Topic should auto clear upon raid end, and a newsflash added?(Temporary news item that spams upon login for a set amount of time and has a limited amount of characters). Feel free to make suggestions about newsflash though, just some quick ideas

**Comment by bigwheels16** [comment]
Regarding news flash, the basic news module does that by default.  Do we need more than that?

**Comment by Teeko1993** [comment]
It only gives you a listing of the currents news doesn't it? I imagine
newsflash being something that was limited to maybe 100 characters or
something and only lasted a few days, maybe a week at most before clearing
itself. This would allow us to push urgent news to org members without
worrying about them clicking on the news link, which some just don't do.

**Comment by bigwheels16** [comment]
The point of the news module is to push news to members.  So if it's not doing that effectively, we need to change how the news module works so it does that rather than just add more functionality to it.

But I really think it is doing that effectively.  Having an option to mark news as read so it doesn't pop up every time makes the news more likely to be read, IMO.  And based on Lightnet logs, lots of people are marking the news items as read, which means they are clicking the link to open it up.

**Comment by bigwheels16** [comment]
if we do need to change the news module, let's create a new ticket for that
