### ISSUE TITLE
investigate auto invite behavior

### ISSUE THREAD

**Issue by Teeko1993** [Budabot/Tyrbot#66]
Budabot behavior: `!autoinvite on` automatically grants someone the member access level and adds them to buddy list with auto invite on. Alts of `member` access level can use this to add their alts to the bot.

Tyrbot behavior: `!autoinvite on` only invites someone if they were already on the member list. Alts cannot use this to add themselves to the bot.

We need to decide how we want this command to work in the future.

**Comment by bigwheels16** [comment]
this feature, while convenient, opens the possibility for access level escalation through the use of alts.  therefore, we will not implement this feature at this time.  however, if this feature becomes sought after, we may reconsider since the access level escalation is low and the situation that leads to it is somewhat specialized.
