### ISSUE TITLE
Update flag for startup scripts

### ISSUE THREAD

**Issue by einarf** [Budabot/Tyrbot#79]
## Summary of discussion on discord

We should add an update flag to both `startup.bat` and `startup.sh` that will do a `git pull` when starting/restarting bot. Info about this should be in `README.md` possibly also linking to git download for windows users.

When not passing the flag to scripts the auto updating will not happen. This gives users more control. It's not uncommon for users to mess with files increasing the chance for merge conflicts during `git pull`.

See `dev.sh` for reference. Add flag check.

EDIT: This flag should probably be optional. If not present, no updating will happen. Users have to opt in by providing the flag.

**Comment by bigwheels16** [comment]
I realize this is an old issue, but I will respond anyways since I guess I missed it before.  This is not something we want to support.  If users want this, they are encouraged to write their own startup script.  The other option would be to run Tyrbot in Docker, which is now published at https://hub.docker.com/r/bigwheels16/tyrbot.  The "latest" tag contains the very latest changes from the master branch.
